version: '3.8'

services:
  dna:
    container_name: ${COMPOSE_PROJECT_NAME}_dna
    image: ${COMPOSE_PROJECT_NAME}/dna:local
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
