name: Testing

on:
  push:
    branches: [ release/**, hotfix/**, bugfix/** ]
  pull_request:
    branches: [ main, develop, release/**, hotfix/**, bugfix/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          DNA_CHARS: ${{ secrets.DNA_CHARS }}
          DNA_MUTATION_THRESHOLD_CHARS_COUNT: ${{ secrets.DNA_MUTATION_THRESHOLD_CHARS_COUNT }}
          DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH: ${{ secrets.DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH }}
      - name: Testing
        run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
