name: Testing

on:
  push:
    branches: [ release/**, hotfix/**, bugfix/**, feature/**  ]
  pull_request:
    branches: [ main, develop, hotfix/**, bugfix/**, feature/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: yarn install
      - run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        env:
          DNA_CHARS: ${{ env.DNA_CHARS }}
          DNA_MUTATION_THRESHOLD_CHARS_COUNT: ${{ env.DNA_MUTATION_THRESHOLD_CHARS_COUNT }}
          DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH: ${{ env.DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH }}
