name: Testing

on:
  push:
    branches: [ release/**, hotfix/**, bugfix/**, feature/**  ]
  pull_request:
    branches: [ main, develop, hotfix/**, bugfix/**, feature/** ]

jobs:
  build:

    environment: testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: yarn install
      - run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        env:
          DNA_CHARS: ${{ secrets.DNA_CHARS }}
          DNA_MUTATION_THRESHOLD_CHARS_COUNT: ${{ secrets.DNA_MUTATION_THRESHOLD_CHARS_COUNT }}
          DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH: ${{ secrets.DNA_MUTATION_THRESHOLD_SEQUENCE_LENGTH }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_AUTH_MECHANISM: ${{ secrets.DB_AUTH_MECHANISM }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: yarn test
